### ISSUE TITLE
the battery percentage is not aligned with the battery icon in the quick settings

### ISSUE THREAD

**Issue by houssemko** [maniacx/Bluetooth-Battery-Meter#18]
i'm using a custom shell theme , whitsur gtk theme 
![image](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/41808005/154176b2-67a1-47f9-beb2-39e0e0656971)

**Comment by maniacx** [comment]
Can u give me additional details?
OS: (ex Fedora 39, ubuntu 22.10)?
Gnome -shell version you are using: (example 43,44, or 45)?

And also a screenshot with the extension disabled.
* disable bluetooth battery meter extension. 
* Log out and re-login
* Post the screenshot of bluetooth menu.

**Comment by houssemko** [comment]
i'm running garuda linux , gnome 45.3 wayland session
the bluetooth menu with the extension disabled
![image](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/41808005/b1e32bfa-76bb-4ebd-9e78-9c458984722b)

**Comment by maniacx** [comment]
![2](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/4295343/87620be9-9fa7-49b1-b924-4d01c84f7073)


As you can see in the above picture posted by you, the issue is not with the extension. But something to do with the theme.
Even without the extension, the `headphone icon `is not aligned with the text` Hama Spirit `and ` Redmi Bus`.

However just for testing I did install WhieSur on Fedora 39 Gnome 45, I dont have the issue you described with extension enabled or disabled. The icons are aligned with text. Below are pics of bluetooth menu with extension enabled and disabled,

![Screenshot from 2024-02-05 17-56-38](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/4295343/a8c01248-64d0-4985-be14-4311c413ab81)
![Screenshot from 2024-02-05 17-56-59](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/4295343/0ffa437c-8a9b-4b63-bfe1-020f717752c0)


Conclusion

* It is definately not the extension causing it.
* It could be the theme not compatable with your system.
* It could be an theme installation issue.


For theme installation I just ran `sudo (path to theme director)/install.sh -t all`
And then using Gnome tweak I selected dark purple theme.

**Comment by houssemko** [comment]
yeah i agree  it's the theme causing the  problem , but why did you use sudo to apply the theme?

**Comment by maniacx** [comment]
Yes you are correct. We do not need sudo to apply the theme. I misread the installation.
With sudo the whitesur theme get installed at /usr/share/themes
Without sudo it get installed at ~/.themes

Either case with or without sudo the text and icons are aligned on my system. Are you using any special arguments when running ./install.sh?

**Comment by houssemko** [comment]
yes i'm using these arguments :
./install.sh -o normal -c Dark -t purple -l --normal --darker

**Comment by maniacx** [comment]
I  unistalled all themes and used

`
./install.sh -o normal -c Dark -t purple -l --normal --darker
`
And choose the theme in Gnome-tweaks.
I have text and icons aligned. 

You can close the issue if there are no further question.

**Comment by houssemko** [comment]
Yes I'll transfer the issue to the theme maker github
